[project]
name = "knoxx_class_mods_everywhere"
version = "1.0.0"
authors = [{ name = "sp4ky" }]
description = "Makes the class mods from The Secret Armory of General Knoxx drop from enemies everywhere. Inspired by Yeti's BL1-only QoLSlop."
dependencies = ["willow1_mod_manager >= 2.3"]

[tool.sdkmod]
name = "Knoxx Class Mods Everywhere"
version = "1.0.0"
supported_games = ["BL1", "BL1E"]
coop_support = "HostOnly"
download = "https://github.com/sp4ky/bl1-sdk-mods/raw/refs/heads/main/knoxx_class_mods_everywhere/knoxx_class_mods_everywhere.sdkmod"
license = {name = "GPL3", url = "https://choosealicense.com/licenses/gpl-3.0/"}
